### ISSUE TITLE
一直尝试激活中，激活不成功？

### ISSUE THREAD

**Issue by wangkerong** [OdysseusYuan/LKY_OfficeTools#10]
![image](https://github.com/OdysseusYuan/LKY_OfficeTools/assets/44842104/54608839-cb95-47a6-a1ef-e89b0859047c)

系统win11

**Comment by OdysseusYuan** [comment]
感谢使用本工具。辛苦检查下系统的日期和时间，以及时区是否正确。如开启了科学上网工具，建议您暂时先关闭。以上确认正确后重新运行本工具，看看是否可以解决。感谢您的反馈，有问题随时沟通。
