### ISSUE TITLE
想跟您询问，您是否愿意提供繁体中文(zh-tw)LKY_OfficeTools

### ISSUE THREAD

**Issue by htcren** [OdysseusYuan/LKY_OfficeTools#13]
您好：

想跟您询问，您是否愿意提供
LKY_OfficeTools 繁体中文(zh-tw)的自动化下载档
因为您的程式真的太厉害方便好用
但是目前执行只能自动安装简体中文(zh-cn)

还请您协助万分感激

**Comment by OdysseusYuan** [comment]
感谢您的使用。目前多国语言暂时还不支持，但基于您的建议，我会在后续迭代中陆续增加跨语言支持。感谢您的建议。

**Comment by htcren** [comment]
謝謝您的支持

**Comment by htcren** [comment]
谢谢您的支持
