### ISSUE TITLE
请问是否可以支持选择性安装

### ISSUE THREAD

**Issue by 907598940** [OdysseusYuan/LKY_OfficeTools#15]
像一些Outlook，Onedrive
这些功能根本不需要。也会占用C盘存储。能否可以像office plus 一样，支持选择安装内容

**Comment by OdysseusYuan** [comment]
感谢您的使用。后续我会随着迭代，提供自定义组件增减的功能，敬请关注。非常感谢您的建议。

**Comment by chenbihao** [comment]
刚需

**Comment by OdysseusYuan** [comment]
感谢您的建议，本需求已经在需求池中，且为高优先级，下个月会迭代上线，敬请关注。

以上，感谢您的使用。如有问题随时沟通。

 

发件人: 陈壁浩
发送时间: 2023年6月15日 11:59
收件人: OdysseusYuan/LKY_OfficeTools
抄送: OdysseusYuan; State change
主题: Re: [OdysseusYuan/LKY_OfficeTools] 请问是否可以支持选择性安装 (Issue #15)

刚需

**Comment by OdysseusYuan** [comment]
两位好，新版本已经上线，本次迭代已实现两位的诉求，详情请见：https://github.com/OdysseusYuan/LKY_OfficeTools/releases/tag/v1.2.1
