### ISSUE TITLE
i640.cab文件下载错误 手动 访问网址也不行

### ISSUE THREAD

**Issue by Daohuai0913** [OdysseusYuan/LKY_OfficeTools#16]
05/18 00:27:31 [ERROR] CUID#7 - Download aborted. URI=http://officecdn.microsoft.com/pr/5030841d-c919-4594-8d2d-84ae4f96e58e/office/data/16.0.14332.20303/i640.cab
Exception: [AbstractCommand.cc:351] errorCode=22 URI=http://officecdn.microsoft.com/pr/5030841d-c919-4594-8d2d-84ae4f96e58e/office/data/16.0.14332.20303/i640.cab&supercache=1
  -> [HttpSkipResponseCommand.cc:239] errorCode=22 The response status is not successful. status=400

05/18 00:27:31 [NOTICE] Download GID#e0e8db1cb584c700 not complete: C:/Users/wjz/Desktop/Office/Data/16.0.14332.20303/i640.cab

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
e0e8db|ERR |       0B/s|C:/Users/wjz/Desktop/Office/Data/16.0.14332.20303/i640.cab

![image](https://github.com/OdysseusYuan/LKY_OfficeTools/assets/31792646/7dc99544-b5db-4722-b196-484c79e44b3e)

**Comment by Daohuai0913** [comment]
![image](https://github.com/OdysseusYuan/LKY_OfficeTools/assets/31792646/e29a6693-0d8a-4bb8-a666-960b323ccdd3)

**Comment by OdysseusYuan** [comment]
感谢您的使用。本工具涉及到office的文件均来源于官网原版，未经任何修改。故下载时，若官网地址不可用，则下载会出现问题。经测试，目前该链接已可用。您可以重新运行本工具即可下载完成。以上，感谢您的反馈。
