### ISSUE TITLE
安装SN失败

### ISSUE THREAD

**Issue by jinihou** [OdysseusYuan/LKY_OfficeTools#17]
![image](https://github.com/OdysseusYuan/LKY_OfficeTools/assets/133932705/8c613edc-33bd-415c-be23-663cba99b9e6)
请帮忙看一下这个报错。没用科学上网，时区时间也是对的。谢谢。

**Comment by OdysseusYuan** [comment]
感谢您的使用。您之前有安装过旧版本/其他版本的office么？

**Comment by jinihou** [comment]
有。用您这个工具的时候已经删除旧版本了。

**Comment by OdysseusYuan** [comment]
您好，新版本已经上线，本次迭代已解决安装序列号的问题，详情请见：https://github.com/OdysseusYuan/LKY_OfficeTools/releases/tag/v1.2.1
