### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by Sword6988** [OdysseusYuan/LKY_OfficeTools#18]
大佬有考虑出一版默认只安装ppt，word，excel三件套版本吗，我觉得大部分人其实只装这三个就够了

**Comment by OdysseusYuan** [comment]
感谢您的使用。您的建议已经放入我的需求池中，后期将会推出，敬请关注。

**Comment by Sword6988** [comment]
感谢！！！

**Comment by thorlab** [comment]
除了ppt，word，excel，还有visio是否能集成进来，四件套哈哈

**Comment by Sword6988** [comment]
> 除了ppt，word，excel，还有visio是否能集成进来，四件套哈哈

那你还不如用office tools定制呢，大部分人最常用的还是三件套，visio毕竟太小众了

**Comment by OdysseusYuan** [comment]
两位好，新版本已经上线，本次迭代已实现两位的诉求，详情请见：https://github.com/OdysseusYuan/LKY_OfficeTools/releases/tag/v1.2.1
