### ISSUE TITLE
win10版本要求有点高

### ISSUE THREAD

**Issue by wu89053** [OdysseusYuan/LKY_OfficeTools#2]
大佬，能不能把安装版本降到win10(1607)以下，谢谢！

**Comment by OdysseusYuan** [comment]
感谢你的反馈。本软件安装做出系统限制，主要基于以下考虑：
1、最新版本的 Office 和 Win10 (1607) 及更早系统的兼容性很差，无论是安装还是授权。
2、微软官方对 Win10 (1607)  停止一切维护的截止时间是：2019年4月，此后该版本的系统不会被提供任何安全层面的维护（https://learn.microsoft.com/zh-cn/lifecycle/announcements/windows-10-1607-end-of-servicing）。最新版 Office 与该版本系统不兼容，可能原因也正是如此。
3、Win 10 从第一个首发正式版开始，只要有新的稳定版推送，用户一联网就会被强制升级。
4、因为本软件采用的是“正版授权”的方式，激活需要互联网环境，外加上面的第3条，用户维持在早期Win版本的概率不大。
所以基于以上情况，做了系统限制。

但如果楼主有这方面的诉求，我后期进行软件主体完善时，可能会考虑增加对早期系统的支持，以上，再次感谢你的使用和反馈。
