### ISSUE TITLE
win 11安装失败

### ISSUE THREAD

**Issue by zer07z** [OdysseusYuan/LKY_OfficeTools#20]
代理已关闭，时区如下图，报错如下图
![image](https://github.com/OdysseusYuan/LKY_OfficeTools/assets/91652536/23d63f78-d637-4e74-9e4d-291b164b7b20)
![image](https://github.com/OdysseusYuan/LKY_OfficeTools/assets/91652536/ca682d2f-435a-47b4-99b9-dee9d70a3742)

**Comment by OdysseusYuan** [comment]
感谢您的使用。目前新版本已经发布，可以尝试使用：https://github.com/OdysseusYuan/LKY_OfficeTools/releases/tag/v1.2.1

**Comment by zer07z** [comment]
新版依旧报错，请问有无排查方案？
![image](https://github.com/OdysseusYuan/LKY_OfficeTools/assets/91652536/17c196c0-1d49-403f-a9b1-65373406a985)

**Comment by goodwin-lvzhou** [comment]
> 新版依旧报错，请问有无排查方案？ ![image](https://user-images.githubusercontent.com/91652536/252297740-17c196c0-1d49-403f-a9b1-65373406a985.png)

me too,坐等解決方案，感謝作者，支持作者。
