### ISSUE TITLE
如何卸载？（卸载后重启6件套又回来了）

### ISSUE THREAD

**Issue by lijinpeng1980** [OdysseusYuan/LKY_OfficeTools#22]
https://gitee.com/OdysseusYuan/LKY_OfficeTools/issues/I79YD1
Gitee上反馈询问没人理会，所以来这里留言了。
卸载后重启电脑，6件套又回来了。用官方卸载工具卸载后，当时重启6件套不会回来，但过几天，不知道哪次重启，这6件套就又回来了。请问如何彻底卸载？

**Comment by OdysseusYuan** [comment]
感谢您的使用。您可尝试下载最新版工具，新工具已经针对该问题进行了部署：https://github.com/OdysseusYuan/LKY_OfficeTools/releases/tag/v1.2.1，安装后，在“控制面板”选择卸载Office，再次重启即可解决此问题。
