### ISSUE TITLE
使用LKY_OfficeTools 1.2.1安装的office无法使用连接账户

### ISSUE THREAD

**Issue by ninespriing** [OdysseusYuan/LKY_OfficeTools#23]
![image](https://github.com/OdysseusYuan/LKY_OfficeTools/assets/22248829/7d6ca711-1ff7-49f0-bbe1-9df0a206e2da)
![image](https://github.com/OdysseusYuan/LKY_OfficeTools/assets/22248829/66ceaf6d-d38a-49ef-9e13-cfac0ea8d3e7)
![image](https://github.com/OdysseusYuan/LKY_OfficeTools/assets/22248829/b24f74d4-a223-4c57-ab51-d233ed822829)

**Comment by OdysseusYuan** [comment]
感谢您的使用。如果您使用了网络代理工具，可以在关闭后再次尝试。
