### ISSUE TITLE
office全给我卸载干净了，却安装失败了。。

### ISSUE THREAD

**Issue by leef2464** [OdysseusYuan/LKY_OfficeTools#25]
![image](https://github.com/OdysseusYuan/LKY_OfficeTools/assets/143598182/b272e272-c704-4a3c-905f-e162c33f5567)

**Comment by OdysseusYuan** [comment]
感谢您的使用。您可以尝试重启电脑后再次运行本工具。

**Comment by shuimeijinjinjin** [comment]
(´థ౪థ)σ 一进来想看看大家评论，被你这一句话给笑喷了
