### ISSUE TITLE
卡在开头

### ISSUE THREAD

**Issue by ouandel** [OdysseusYuan/LKY_OfficeTools#26]
我下载了所有需要的文件后，安装却卡在了开头

![WM-Screenshots-20230907213313](https://github.com/OdysseusYuan/LKY_OfficeTools/assets/58887251/1a4e7291-6bb6-441b-8802-06f332923486)

**Comment by OdysseusYuan** [comment]
感谢您的使用。您可以尝试重启电脑后再次运行，其目的是为了确保系统中不存在多余的CTR进程。
