### ISSUE TITLE
win10 1909 安装失败，网络是好的，空间还有 50G

### ISSUE THREAD

**Issue by neohob** [OdysseusYuan/LKY_OfficeTools#27]
<img width="488" alt="image" src="https://github.com/OdysseusYuan/LKY_OfficeTools/assets/1756648/e6675fe3-6acb-40f5-a140-60c57e73998c">

**Comment by OdysseusYuan** [comment]
感谢您的使用。您可以尝试重启计算机后再次运行本工具，看下问题是否解决。

**Comment by neohob** [comment]
谢谢回复，重启过也没用，就是不知道啥问题，这个应该没有 log 可以看到

**Comment by blurm** [comment]
一样是1909，基本是新装系统，一样的问题

**Comment by OdysseusYuan** [comment]
感谢两位的反馈。目前我已经复核该问题，原因为：微软已停止对1909版本的支持，具体链接如下：https://learn.microsoft.com/zh-cn/lifecycle/announcements/windows-10-1909-enterprise-education-eos
以上，再次感谢两位的反馈。
