### ISSUE TITLE
设置激活载体失败

### ISSUE THREAD

**Issue by Einzieg** [OdysseusYuan/LKY_OfficeTools#28]
![image](https://github.com/OdysseusYuan/LKY_OfficeTools/assets/94288565/e11c3f4d-5f0b-449d-8959-74babf1e3084)

**Comment by OdysseusYuan** [comment]
感谢您的使用。您可尝试升级系统到最新版系统，具体操作如下：“桌面”右键 -> 个性化 -> 主页 -> 更新和安全 -> 检查更新。待系统升级到最新版后，再次运行本工具，理应解决上述问题。以上，感谢您的反馈，如有问题可随时沟通。

**Comment by Einzieg** [comment]
> 感谢您的使用。您可尝试升级系统到最新版系统，具体操作如下："桌面"右键 -> 个性化 -> 主页 -> 更新和安全 -> 检查更新。待系统升级到最新版后，再次运行本工具，理应解决上述问题。以上，感谢您的反馈，如有问题可随时沟通。

更新系统后就可以了，谢谢大佬
