### ISSUE TITLE
请问可以添加一个软件卸载功能吗?

### ISSUE THREAD

**Issue by winner106** [OdysseusYuan/LKY_OfficeTools#3]
使用系统自带的卸载功能无法干净清除软件，官方的卸载工具也是无法检测到这个安装版本，我是正好最近安装的 Excel 插件有点多，可能把 Excel 搞坏了，所以想完全卸载它然后重新安装一次。

但一直搞不定，如果直接重新用您的程序安装的话，会一直卡在安装界面。即使我用系统的卸载功能卸载了程序，但重启后程序依然存在，不知道是什么情况。

![直接再次运行卡在安装界面](https://user-images.githubusercontent.com/50519642/211274791-87130e0b-9561-417f-8b81-d2a0cb707105.png)

**Comment by OdysseusYuan** [comment]
感谢您的使用。请问一下，您卡在这个界面大约持续多长时间了？

**Comment by winner106** [comment]
您好，感谢回复。刚才又试了一次，我先用系统的卸载功能卸载了office，然后重启电脑，再用您的工具再重新安装Office，就出现卡在以上界面，起码有 1 小时以上了，现在也还没有结束。
系统是 win11 22H2

**Comment by OdysseusYuan** [comment]
收到，了解。您可以尝试使用这个工具实现office清除：[https://outlookdiagnostics.azureedge.net/sarasetup/SetupProd_OffScrub.exe](https://outlookdiagnostics.azureedge.net/sarasetup/SetupProd_OffScrub.exe)
但无论上述方法是否成功，我都建议您重新安装操作系统。一般来说，安装office时，长时间卡在如您图中所示的界面时，往往与您的系统文件遭到了破坏有关，进而导致安装不能继续。这一问题尽管通过清理office的方法，暂时不显现了，但您在后续使用计算机时，仍然有大概率会出现其它意外的问题。

**Comment by winner106** [comment]
谢谢，已通过官方渠道下载 office 重新安装成功了，感谢指引

**Comment by OdysseusYuan** [comment]
很开心看到您解决了问题，同时非常感谢您的反馈，如您后续有任何问题，欢迎随时沟通。以上，祝生活愉快。
