### ISSUE TITLE
請問可以轉語言嗎

### ISSUE THREAD

**Issue by rexxx428** [OdysseusYuan/LKY_OfficeTools#33]
安裝很順利 過程十分順暢!
只是我想轉語言的時侯去了文件>選項>語言裡面安裝不了英文
除此之外實在做得太好了 超快速方便!!

**Comment by OdysseusYuan** [comment]
感谢您的使用。目前，您可尝试如下手动操作完成语言切换：

1、确保已通过本工具安装了计划使用的组件（如：Word、PPT、Excel等）。
2、下载英文语言包补丁（根据您的版本选择一个）：[x64位版](https://c2rsetup.officeapps.live.com/c2r/download.aspx?ProductreleaseID=languagepack&language=en-us&platform=x64&source=O16LAP&version=O16GA) | [x64位版](https://c2rsetup.officeapps.live.com/c2r/download.aspx?ProductreleaseID=languagepack&language=en-us&platform=x86&source=O16LAP&version=O16GA)；
3、双击下载后的exe文件，稍等一段时间后将自动开始安装英文语言包：
![image](https://github.com/OdysseusYuan/LKY_OfficeTools/assets/115532436/b742a471-2758-4d8e-91a4-af40631a454a)
4、安装完成后，启动Office任一款子产品（如：Word）。并在 文件 -> 选项 -> 语言 中按照下图设置英文语言：
![image](https://github.com/OdysseusYuan/LKY_OfficeTools/assets/115532436/45471dcd-635f-4d81-a775-1da7c2f90c89)
5、设置好后，重启Office产品后，英文界面自动生效。

以上，如有问题，欢迎继续沟通，感谢您的反馈与支持。

**Comment by rexxx428** [comment]
成功了 感謝你!
快捷又方便

**Comment by OdysseusYuan** [comment]
楼主您好，基于您此前的应用场景，目前已经开发多国语言版，并进入灰测阶段，开发代号为：Mocreak。

这是一个基于当前工具开发的衍生版本，支持43种语言，您可在安装时直接选择将英语作为默认语言。

您可尝试下载体验，连接地址为：[https://github.com/OdysseusYuan/Mocreak/releases/latest](https://github.com/OdysseusYuan/Mocreak/releases/latest)
