### ISSUE TITLE
可以加个完全卸载的功能吗

### ISSUE THREAD

**Issue by Slmtdhy** [OdysseusYuan/LKY_OfficeTools#34]

**Comment by networkxiake** [comment]
对，有时不需要用了又卸载不干净。

**Comment by OdysseusYuan** [comment]
感谢两位的使用。你们的建议非常有用，后期会进入排期完成开发，感谢两位的支持和反馈。

**Comment by OdysseusYuan** [comment]
两位好，你们的需求已经完成开发，并进入灰测阶段，开发代号为：Mocreak。

这是一个基于当前工具开发的衍生版本，该版本已经支持仅彻底卸载 Office 功能。

您可尝试下载体验，连接地址为：[https://github.com/OdysseusYuan/Mocreak/releases/latest](https://github.com/OdysseusYuan/Mocreak/releases/latest)
