### ISSUE TITLE
请问支持win7 2019年最后的版本吗

### ISSUE THREAD

**Issue by matocool** [OdysseusYuan/LKY_OfficeTools#36]
请问支持win7 2019年最后的版本吗

2016年7月及其之前发布的 Windows 系统（即：Windows 10(1703) 之前的系统）

根据描述，2016.7之后不再支持。但是2019 win7旗舰版还有一次更新。

还有就是我发现安装的版本似乎有点随机？本人win11 x64 安装的是 LTSC版本的，但是我看到有人装的是别的版本。而且比如说我想指定安装office2016如何实现呢。。。。

**Comment by OdysseusYuan** [comment]
楼主您好，您的需求已经尝试开发，并进入灰测阶段，开发代号为：Mocreak。

这是一个基于当前工具开发的衍生版本，该版本已经尝试性的将 Office 支持到了 win7 系统。

您可尝试下载体验，连接地址为：[https://github.com/OdysseusYuan/Mocreak/releases/latest](https://github.com/OdysseusYuan/Mocreak/releases/latest)
