### ISSUE TITLE
希望加入其他默认语言

### ISSUE THREAD

**Issue by lisai9093** [OdysseusYuan/LKY_OfficeTools#37]
比如英语，身在国外英语还是更方便点。。。省的再去找语言包安装了

**Comment by OdysseusYuan** [comment]
感谢您的使用。您提出的多语言支持需求已经进入开发需求池，后期将陆续上线。

**Comment by OdysseusYuan** [comment]
楼主您好，您的需求已经完成开发，并进入灰测阶段，开发代号为：Mocreak。

这是一个基于当前工具开发的衍生版本，已经支持多国语言。

您可尝试下载体验，连接地址为：[https://github.com/OdysseusYuan/Mocreak/releases/latest](https://github.com/OdysseusYuan/Mocreak/releases/latest)
