### ISSUE TITLE
一直激活失败怎么办？

### ISSUE THREAD

**Issue by HT944** [OdysseusYuan/LKY_OfficeTools#38]

**Comment by OdysseusYuan** [comment]
感谢您的使用。可否上一下截图？

**Comment by mekumiao** [comment]
![image](https://github.com/OdysseusYuan/LKY_OfficeTools/assets/48587985/7f7046d1-2e03-4d2e-88f4-a34cd5e7606f)
一直激活失败

**Comment by edgeman03** [comment]
是的，也有出现这个情况。后面是用第三方的激活工具搞定的。感觉像工具内置的KMS激活都失效了一样

**Comment by OdysseusYuan** [comment]
感谢大家的使用。目前我已在积极解决此问题，近期将会上线新版工具，敬请期待。非常感谢大家的反馈。

**Comment by mekumiao** [comment]
我安装完成后，用的KMS方法激活的。[原文链接](https://www.orcy.net.cn/1854.html)
![image](https://github.com/OdysseusYuan/LKY_OfficeTools/assets/48587985/585779b8-d0c6-49e1-b2b5-600bd55c3ff2)
