### ISSUE TITLE
可否选择安装的组件

### ISSUE THREAD

**Issue by zhmstar0310** [OdysseusYuan/LKY_OfficeTools#4]
大部分情况下只需要安装word，excel& ppt，如果可以选择就更好了

**Comment by OdysseusYuan** [comment]
感谢您的使用。您的建议已被采纳，后续会陆续上线，敬请期待。感谢您的建议。

**Comment by OdysseusYuan** [comment]
您好，新版本已经上线，本次迭代已支持选配安装，详情请见：https://github.com/OdysseusYuan/LKY_OfficeTools/releases/tag/v1.2.1
