### ISSUE TITLE
一直在卸载 office ODT版本

### ISSUE THREAD

**Issue by looooading** [OdysseusYuan/LKY_OfficeTools#42]
![image](https://github.com/OdysseusYuan/LKY_OfficeTools/assets/54234042/d48ba82a-4fd5-4bd9-bf21-bae35e155014)

**Comment by looooading** [comment]
one note和one drive好像一直卸不掉
![image](https://github.com/OdysseusYuan/LKY_OfficeTools/assets/54234042/215b69d2-bf8a-4bc4-bf3f-fb8e517b17fe)

**Comment by looooading** [comment]
![image](https://github.com/OdysseusYuan/LKY_OfficeTools/assets/54234042/27087abc-6fd1-46c5-ab3d-ddfb867707c5)

**Comment by looooading** [comment]
我是买电脑的时候送的2019学生版

**Comment by OdysseusYuan** [comment]
感谢您的使用。ODT组件因Windows系统补丁更新，引发了卸载困难等问题，目前我已经联系相关团队解决，其将在下月发布KB补丁以修复此问题，感谢您对微软中国的支持。同时，本工具也将赶在微软补丁上线前，提供有效的解决方案，目前已经在研发中，近期将会上线，敬请期待。

**Comment by OdysseusYuan** [comment]
楼主您好，关于您提到的问题，本工具已经抢先修复（微软修复时间为2月中旬），并进入灰测阶段，开发代号为：Mocreak。

这是一个基于当前工具开发的衍生版本，解决了 ODT 卸载卡住的问题，此外，该版本还支持多国语言、支持 Office 2024，支持仅彻底卸载 Office 功能。

您可尝试下载体验，连接地址为：[https://github.com/OdysseusYuan/Mocreak/releases/latest](https://github.com/OdysseusYuan/Mocreak/releases/latest)
