### ISSUE TITLE
安装完成重启之后电脑屏幕一直闪烁

### ISSUE THREAD

**Issue by BFmHNO3** [OdysseusYuan/LKY_OfficeTools#43]
Windows 11 23H2

**Comment by OdysseusYuan** [comment]
感谢您的使用。可否进一步描述下细节内容？是屏幕闪烁，还是桌面不断刷新？近期是否有更新显卡/驱动，或者有安装什么新的系统补丁？

**Comment by BFmHNO3** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by BFmHNO3** [comment]
的确更新了系统的，`Windows 11 家庭用户版`。后来证明的确是系统更新的问题，因为卸载了系统更新之后，电脑正常开机……

**Comment by bfmhno3** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
