### ISSUE TITLE
新功能需求

### ISSUE THREAD

**Issue by manuall** [OdysseusYuan/LKY_OfficeTools#44]
当前安装后默认为中文，无法跟随系统语言（英文），请求添加英文版本。

**Comment by OdysseusYuan** [comment]
感谢您的使用。您的需求正在开发，近期将会上线，敬请期待。感谢您的建议。

**Comment by OdysseusYuan** [comment]
楼主您好，您的需求已经完成开发，并进入灰测阶段，开发代号为：Mocreak。

这是一个基于当前工具开发的衍生版本，支持多国语言、支持 Office 2024，支持仅彻底卸载 Office 功能。

您可尝试下载体验，连接地址为：[https://github.com/OdysseusYuan/Mocreak/releases/latest](https://github.com/OdysseusYuan/Mocreak/releases/latest)
