### ISSUE TITLE
怎么选择安装目录？

### ISSUE THREAD

**Issue by luckpig24678** [OdysseusYuan/LKY_OfficeTools#45]
怎么选择安装目录？

**Comment by OdysseusYuan** [comment]
感谢您的关注。当前版本暂不支持选择安装目录。您的需求已经被记录，后续将进一步评估可行性。以上，感谢您的支持。

**Comment by OdysseusYuan** [comment]
您好，您的需求已经开发完成，并进入第二阶段灰测阶段，开发代号为：Mocreak。

这是一个基于当前工具开发的图形化版本，**_已支持自定义安装分区位置_**，此外，该版本还支持多国语言、支持 Office 2024，支持仅彻底卸载 Office 等功能。

您可尝试下载体验，连接地址为：https://github.com/OdysseusYuan/Mocreak/releases/latest
