### ISSUE TITLE
多次激活均不成功

### ISSUE THREAD

**Issue by 965652556** [OdysseusYuan/LKY_OfficeTools#46]
多次激活均不成功
![ITYPL7R{6_Q`W%2IR1K9M)G](https://github.com/OdysseusYuan/LKY_OfficeTools/assets/68040152/cd9d108d-ff0c-4d41-9b41-31c4a52deee4)

**Comment by OdysseusYuan** [comment]
感谢您的使用，您可尝试下使用图形化版本：https://www.mocreak.com
