### ISSUE TITLE
只能安装最新版的office吗？

### ISSUE THREAD

**Issue by jlmoto1** [OdysseusYuan/LKY_OfficeTools#48]
可否自定义安装所需的office版本，比如选择2016等，有些office版本太高，与其他计算机不好兼容？

**Comment by OdysseusYuan** [comment]
感谢您的使用。

的确，目前仅支持安装最新版，如需 2021 版，可通过 Mocreak 安装“稳定版”实现：https://www.mocreak.com

此前不考虑支持 2016、2019 版，是基于产品生命周期考虑：
1、早期 Office 即将停止（相应的 365 服务已于去年停止）一切服务支持：https://learn.microsoft.com/zh-cn/deployoffice/endofsupport/resources#past-end-of-support-events
2、可 90% 兼容早期 Office 的 Windows 10 操作系统也将同期停止一切服务支持：https://learn.microsoft.com/zh-cn/lifecycle/announcements/windows-10-22h2-end-of-support-update

但考虑到您的诉求，后续仍可能融合早期 Office 版本，以帮助您完成 Office 体验与改善的平衡，感谢您的建议。
