### ISSUE TITLE
下载 i640.cab 失败

### ISSUE THREAD

**Issue by 007ayong** [OdysseusYuan/LKY_OfficeTools#49]
05/16 15:34:32 [ERROR] CUID#11 - Download aborted. URI=udp://93.158.213.92:1337/announce?info_hash=%DD%84~%95%F3%5Ef%A8w4%9A%09%A1%A6~%2By%9BB%F0&peer_id=-TR2770-t%CB%A8%AC%F3%5D%83%14%2C%BA--&uploaded=0&downloaded=0&left=0&compact=1&key=%F3%5D%83%14%2C%BA--&numwant=50&no_peer_id=1&port=51413&event=started&supportcrypto=1
Exception: [AbstractCommand.cc:351] errorCode=1 URI=udp://93.158.213.92:1337/announce?info_hash=%DD%84~%95%F3%5Ef%A8w4%9A%09%A1%A6~%2By%9BB%F0&peer_id=-TR2770-t%CB%A8%AC%F3%5D%83%14%2C%BA--&uploaded=0&downloaded=0&left=0&compact=1&key=%F3%5D%83%14%2C%BA--&numwant=50&no_peer_id=1&port=51413&event=started&supportcrypto=1
  -> [InitiateConnectionCommandFactory.cc:87] errorCode=1 udp is not supported yet.
[#143a0f 0B/0B CN:0 SD:0 DL:0B]

**Comment by OdysseusYuan** [comment]
感谢您的使用。通常情况下，这是由于官方服务器不稳定造成，稍后即可恢复。
