### ISSUE TITLE
安装到一半进度条不动了

### ISSUE THREAD

**Issue by orinwindy** [OdysseusYuan/LKY_OfficeTools#5]
提示正在安装office 
将很快完成
但是进度条纹丝不动

**Comment by OdysseusYuan** [comment]
感谢你的使用。可以检查一下看看有没有弹窗出现。

**Comment by sjtuross** [comment]
遇到一样的问题，没有任何出错信息，没有弹窗

**Comment by OdysseusYuan** [comment]
辛苦两位朋友帮忙告知下此前安装的office版本可以嘛？

**Comment by OdysseusYuan** [comment]
两次操作中间，有做过其他操作么？比如清理注册表或者删除相关文件。还是说只是重新运行了一下就安装成功了？

**Comment by sjtuross** [comment]
没做过其他操作

**Comment by sjtuross** [comment]
没做过其他操作

**Comment by OdysseusYuan** [comment]
了解。目前也收到了少量用户反馈的同样问题。可以重启后尝试再次运行本工具，看看可否有效解决？据目前分析，很可能是旧版本office卸载后必须重启才能安装新版本。后续迭代时，我会增加相关提示和引导，非常感谢楼上几位的反馈。

**Comment by OdysseusYuan** [comment]
了解。目前也收到了少量用户反馈的同样问题。可以重启后尝试再次运行本工具，看看可否有效解决？据目前分析，很可能是旧版本office卸载后必须重启才能安装新版本。后续迭代时，我会增加相关提示和引导，非常感谢楼上几位的反馈。
