### ISSUE TITLE
产品建议

### ISSUE THREAD

**Issue by book572** [OdysseusYuan/LKY_OfficeTools#54]
能否让用户自行选择安装word、excel和ppt中的一个或多个，而非默认全部安装？

**Comment by sushiltechnex** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by OdysseusYuan** [comment]
感谢您的使用。如需完全自定义组件，请下载图形化版本，各个版本比对/下载详见：https://www.mocreak.com/download.html
