### ISSUE TITLE
安装序列号失败，激活停止

### ISSUE THREAD

**Issue by YanMing-lxb** [OdysseusYuan/LKY_OfficeTools#6]
报错内容如下：
![image](https://user-images.githubusercontent.com/113030089/235842545-8418c0e7-6bad-4a66-a476-326eaf9e3c43.png)

**Comment by OdysseusYuan** [comment]
感谢您的使用。安装序列号失败可能是此前计算机的office仍然有冲突的组件，通常完美的做法是重新安装操作系统，以确保组件的可用性。如您重装操作系统存在一定的不便，可以否方便告知您的公网IP地址？我可以尝试通过 Microsoft 在线激活服务系统尽可能帮您找到失败的原因。
