### ISSUE TITLE
visio能用吗

### ISSUE THREAD

**Issue by zzy-life** [OdysseusYuan/LKY_OfficeTools#7]
可以单独下载visio么？或者下载之后再用这个工具激活

**Comment by OdysseusYuan** [comment]
感谢您的使用。目前visio暂时不会被安装，但是安装后，使用该工具可能被成功激活（暂时没有进行过这方面测试）。但基于您的诉求，后期我会考虑增加更多支持组件。感谢您的咨询和建议。

**Comment by OdysseusYuan** [comment]
您好，新版本已经上线，本次迭代已增设对Visio的支持，详情请见：https://github.com/OdysseusYuan/LKY_OfficeTools/releases/tag/v1.2.1
