### ISSUE TITLE
建议描述中明确操作系统版本，当前只写了“目前已经在 Windows 10(1703) 及以上版本进行了测试”

### ISSUE THREAD

**Issue by Femtometer** [OdysseusYuan/LKY_OfficeTools#8]
而我实测至少要这个版本：

LKY Office Tools [版本 1.1.2.401]
版权所有（C）LiuKaiyuan (Odysseus.Yuan)。保留所有权利。

探讨 LKY Office Tools 相关内容，可发送邮件至：liukaiyuan@sjtu.edu.cn

     × 请将当前操作系统升级至 Windows 10 (1703) 或其以上版本，否则 Office 无法进行正版激活！

请按 任意键 退出 ...

**Comment by OdysseusYuan** [comment]
非常感谢您的使用和建议。基于您的建议，我已更新相关话术，详见：https://github.com/OdysseusYuan/LKY_OfficeTools#%E8%BF%90%E8%A1%8C%E7%8E%AF%E5%A2%83

以上，有任何建议或问题，欢迎随时沟通，再次感谢您的建议。
