### ISSUE TITLE
有关去除Access，或自定义安装

### ISSUE THREAD

**Issue by woyao2291** [OdysseusYuan/LKY_OfficeTools#9]
有些windows会自带Microsoft Access，并且OfficeTools的卸载功能无法将其卸载。
可不可以不集成Access？或者有途径提供手动去除的方法

**Comment by LIUBANGJIAN** [comment]
对，希望可以自定义安装什么套件。

**Comment by OdysseusYuan** [comment]
两位好，新版本已经上线，本次迭代已实现两位的诉求，详情请见：https://github.com/OdysseusYuan/LKY_OfficeTools/releases/tag/v1.2.1
